// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    if (portfolio.conf.is_singular) {
      $('#projects-trigger').toggle(function() {
        return $('#projects').slideDown('fast');
      }, function() {
        return $('#projects').slideUp('fast');
      });
      return $('.slide').fancybox();
    }
  });

}).call(this);
